drop table if exists `currency`;
create table currency (
cry_code char(3) not null,
cry_number char(3) not null,
cry_decimals char(1),
cry_name varchar(255) not null,
cry_countries text,
primary key (cry_code)
) CHARACTER SET utf8 COLLATE utf8_polish_ci;

insert into `currency` (cry_code, cry_number, cry_decimals, cry_name, cry_countries) values
('AED', '784', '2', 'Dirham ZEA', ' Zjednoczone Emiraty Arabskie'),
('AFN', '971', '2', 'Afgani', ' Afganistan'),
('ALL', '008', '2', 'Lek', ' Albania'),
('AMD', '051', '2', 'Dram', ' Armenia'),
('ANG', '532', '2', 'Gulden Antyli Holenderskich', ' Curaçao (CW),  Sint Maarten (SX)'),
('AOA', '973', '2', 'Kwanza', ' Angola'),
('ARS', '032', '2', 'Peso argentyńskie', ' Argentyna'),
('AUD', '036', '2', 'Dolar australijski', ' Australia,  Kiribati (KI),  Nauru (NR),  Norfolk (NF),  Tuvalu (TV),  Wyspa Bożego Narodzenia (CX),  Wyspy Heard i McDonalda (HM),  Wyspy Kokosowe (CC)'),
('AWG', '533', '2', 'Florin arubański', ' Aruba'),
('AZN', '944', '2', 'Manat azerbejdżański', ' Azerbejdżan'),
('BAM', '977', '2', 'Marka zamienna', ' Bośnia i Hercegowina'),
('BBD', '052', '2', 'Dolar barbadoski', ' Barbados'),
('BDT', '050', '2', 'Taka', ' Bangladesz'),
('BGN', '975', '2', 'Lew', ' Bułgaria'),
('BHD', '048', '3', 'Dinar bahrajski', ' Bahrajn'),
('BIF', '108', '0', 'Frank burundyjski', ' Burundi'),
('BMD', '060', '2', 'Dolar bermudzki', ' Bermudy'),
('BND', '096', '2', 'Dolar brunejski', ' Brunei'),
('BOB', '068', '2', 'Boliviano', ' Boliwia'),
('BOV', '984', '2', 'MVDOL boliwijski', ' Boliwia'),
('BRL', '986', '2', 'Real brazylijski', ' Brazylia'),
('BSD', '044', '2', 'Dolar bahamski', ' Bahamy'),
('BTN', '064', '2', 'Ngultrum', ' Bhutan'),
('BWP', '072', '2', 'Pula', ' Botswana'),
('BYN', '933', '2', 'Rubel białoruski', ' Białoruś'),
('BZD', '084', '2', 'Dolar belizeński', ' Belize'),
('CAD', '124', '2', 'Dolar kanadyjski', ' Kanada'),
('CDF', '976', '2', 'Frank kongijski', ' Demokratyczna Republika Konga'),
('CHE', '947', '2', 'WIR Euro (Waluta lokalna)', ' Szwajcaria'),
('CHF', '756', '2', 'Frank szwajcarski', ' Szwajcaria,  Liechtenstein (LI)'),
('CHW', '948', '2', 'WIR Frank (Waluta lokalna)', ' Szwajcaria'),
('CLF', '990', '4', 'Unidad de Fomento', ' Chile'),
('CLP', '152', '0', 'Peso chilijskie', ' Chile'),
('CNY', '156', '2', 'Renminbi', ' Chińska Republika Ludowa'),
('COP', '170', '2', 'Peso kolumbijskie', ' Kolumbia'),
('COU', '970', '2', 'Unidad de Valor Real (UVR)', ' Kolumbia'),
('CRC', '188', '2', 'Colon kostarykański', ' Kostaryka'),
('CUC', '931', '2', 'Peso kubańskie wymienialne', ' Kuba'),
('CUP', '192', '2', 'Peso kubańskie', ' Kuba'),
('CVE', '132', '2', 'Escudo Zielonego Przylądka', ' Republika Zielonego Przylądka'),
('CZK', '203', '2', 'Korona czeska', ' Czechy'),
('DJF', '262', '0', 'Frank Dżibuti', ' Dżibuti'),
('DKK', '208', '2', 'Korona duńska', ' Dania,  Grenlandia (GL),  Wyspy Owcze (FO)'),
('DOP', '214', '2', 'Peso dominikańskie', ' Dominikana'),
('DZD', '012', '2', 'Dinar algierski', ' Algieria'),
('EGP', '818', '2', 'Funt egipski', ' Egipt'),
('ERN', '232', '2', 'Nakfa', ' Erytrea'),
('ETB', '230', '2', 'Birr', ' Etiopia'),
('EUR', '978', '2', 'Euro', ' Unia Europejska (EU),  Andora (AD),  Austria (AT),  Belgia (BE),  Cypr (CY),  Czarnogóra (ME),  Estonia (EE),  Finlandia (FI),  Francja (FR),  Francuskie Terytoria Południowe i Antarktyczne (TF),  Grecja (GR),  Gujana Francuska (GF),  Gwadelupa (GP),  Hiszpania (ES),  Holandia (NL),  Irlandia (IE),  Litwa (LT),  Luksemburg (LU),  Łotwa (LV),  Majotta (YT),  Malta (MT),  Martynika (MQ),  Monako (MC),  Niemcy (DE),  Portugalia (PT),  Reunion (RE),  Saint-Barthélemy (BL),  Saint-Martin (MF),  Saint-Pierre i Miquelon (PM),  San Marino (SM),  Słowacja (SK),  Słowenia (SI),  Watykan (VA),  Włochy (IT),  Wyspy Alandzkie (AX)'),
('FJD', '242', '2', 'Dolar Fidżi', ' Fidżi'),
('FKP', '238', '2', 'Funt falklandzki', ' Falklandy (wymienialny na GBP w stosunku 1:1)'),
('GBP', '826', '2', 'Funt szterling', ' Wielka Brytania,  Brytyjskie Terytorium Oceanu Indyjskiego (IO) (używane także USD),  Wyspa Man (IM, zobacz Funt manx),  Jersey (JE, zobacz Funt Jersey),  Guernsey (GG, zobacz Funt Guernsey)'),
('GEL', '981', '2', 'Lari', ' Gruzja'),
('GHS', '936', '2', 'Cedi', ' Ghana'),
('GIP', '292', '2', 'Funt gibraltarski', ' Gibraltar (wymienialny na GBP w stosunku 1:1)'),
('GMD', '270', '2', 'Dalasi', ' Gambia'),
('GNF', '324', '0', 'Frank gwinejski', ' Gwinea'),
('GTQ', '320', '2', 'Quetzal', ' Gwatemala'),
('GYD', '328', '2', 'Dolar gujański', ' Gujana'),
('HKD', '344', '2', 'Dolar Hongkongu', ' Hongkong'),
('HNL', '340', '2', 'Lempira', ' Honduras'),
('HRK', '191', '2', 'Kuna', ' Chorwacja'),
('HTG', '332', '2', 'Gourde', ' Haiti'),
('HUF', '348', '2', 'Forint', ' Węgry'),
('IDR', '360', '2', 'Rupia indonezyjska', ' Indonezja'),
('ILS', '376', '2', 'Nowy izraelski szekel', ' Izrael,  Palestyna'),
('INR', '356', '2', 'Rupia indyjska', ' Bhutan,  Indie'),
('IQD', '368', '3', 'Dinar iracki', ' Irak'),
('IRR', '364', '2', 'Rial irański', ' Iran'),
('ISK', '352', '0', 'Korona islandzka', ' Islandia'),
('JMD', '388', '2', 'Dolar jamajski', ' Jamajka'),
('JOD', '400', '3', 'Dinar jordański', ' Jordania'),
('JPY', '392', '0', 'Jen', ' Japonia'),
('KES', '404', '2', 'Szyling kenijski', ' Kenia'),
('KGS', '417', '2', 'Som', ' Kirgistan'),
('KHR', '116', '2', 'Riel kambodżański', ' Kambodża'),
('KMF', '174', '0', 'Frank Komorów', ' Komory'),
('KPW', '408', '2', 'Won północnokoreański', ' Korea Północna'),
('KRW', '410', '0', 'Won południowokoreański', ' Korea Południowa'),
('KWD', '414', '3', 'Dinar kuwejcki', ' Kuwejt'),
('KYD', '136', '2', 'Dolar kajmański', ' Kajmany'),
('KZT', '398', '2', 'Tenge', ' Kazachstan'),
('LAK', '418', '2', 'Kip', ' Laos'),
('LBP', '422', '2', 'Funt libański', ' Liban'),
('LKR', '144', '2', 'Rupia lankijska', ' Sri Lanka'),
('LRD', '430', '2', 'Dolar liberyjski', ' Liberia'),
('LSL', '426', '2', 'Loti', ' Lesotho'),
('LYD', '434', '3', 'Dinar libijski', ' Libia'),
('MAD', '504', '2', 'Dirham marokański', ' Maroko,  Sahara Zachodnia'),
('MDL', '498', '2', 'Lej mołdawski', ' Mołdawia'),
('MGA', '969', '2', 'Ariary', ' Madagaskar'),
('MKD', '807', '2', 'Denar', ' Macedonia Północna'),
('MMK', '104', '2', 'Kiat', ' Mjanma'),
('MNT', '496', '2', 'Tugrik', ' Mongolia'),
('MOP', '446', '2', 'Pataca', ' Makau'),
('MRU', '929', '2', 'Ugija', ' Mauretania'),
('MUR', '480', '2', 'Rupia Mauritiusu', ' Mauritius'),
('MVR', '462', '2', 'Rupia malediwska', ' Malediwy'),
('MWK', '454', '2', 'Kwacha malawijska', ' Malawi'),
('MXN', '484', '2', 'Peso meksykańskie', ' Meksyk'),
('MXV', '979', '2', 'Mexican unidad de inversión (UDI)', ' Meksyk'),
('MYR', '458', '2', 'Ringgit', ' Malezja'),
('MZN', '943', '2', 'Metical', ' Mozambik'),
('NAD', '516', '2', 'Dolar namibijski', ' Namibia'),
('NGN', '566', '2', 'Naira', ' Nigeria'),
('NIO', '558', '2', 'Córdoba', ' Nikaragua'),
('NOK', '578', '2', 'Korona norweska', ' Norwegia,  Svalbard i  Jan Mayen (SJ),  Wyspa Bouveta (BV)'),
('NPR', '524', '2', 'Rupia nepalska', ' Nepal'),
('NZD', '554', '2', 'Dolar nowozelandzki', ' Nowa Zelandia,  Niue (NU),  Pitcairn (PN; zobacz także Dolar wysp Pitcairn),  Tokelau (TK),  Wyspy Cooka (CK)'),
('OMR', '512', '3', 'Rial omański', ' Oman'),
('PAB', '590', '2', 'Balboa', ' Panama'),
('PEN', '604', '2', 'Sol', ' Peru'),
('PGK', '598', '2', 'Kina', ' Papua-Nowa Gwinea'),
('PHP', '608', '2', 'Peso filipińskie', ' Filipiny'),
('PKR', '586', '2', 'Rupia pakistańska', ' Pakistan'),
('PLN', '985', '2', 'Polski złoty', ' Polska'),
('PYG', '600', '0', 'Guaraní', ' Paragwaj'),
('QAR', '634', '2', 'Rial katarski', ' Katar'),
('RON', '946', '2', 'Lej rumuński', ' Rumunia'),
('RSD', '941', '2', 'Dinar serbski', ' Serbia'),
('RUB', '643', '2', 'Rubel rosyjski', ' Rosja'),
('RWF', '646', '0', 'Frank rwandyjski', ' Rwanda'),
('SAR', '682', '2', 'Rial saudyjski', ' Arabia Saudyjska'),
('SBD', '090', '2', 'Dolar Wysp Salomona', ' Wyspy Salomona'),
('SCR', '690', '2', 'Rupia seszelska', ' Seszele'),
('SDG', '938', '2', 'Funt sudański', ' Sudan'),
('SEK', '752', '2', 'Korona szwedzka', ' Szwecja'),
('SGD', '702', '2', 'Dolar singapurski', ' Singapur'),
('SHP', '654', '2', 'Funt Świętej Heleny', ' Tristan da Cunha,  Wyspa Świętej Heleny (SH-SH),  Wyspa Wniebowstąpienia (SH-AC)'),
('SLL', '694', '2', 'Leone', ' Sierra Leone'),
('SOS', '706', '2', 'Szyling somalijski', ' Somalia'),
('SRD', '968', '2', 'Dolar surinamski', ' Surinam'),
('SSP', '728', '2', 'Funt południowosudański', ' Sudan Południowy'),
('STN', '930', '2', 'Dobra', ' Wyspy Świętego Tomasza i Książęca'),
('SVC', '222', '2', 'Colón salwadorski', ' Salwador'),
('SYP', '760', '2', 'Funt syryjski', ' Syria'),
('SZL', '748', '2', 'Lilangeni', ' Eswatini'),
('THB', '764', '2', 'Bat', ' Tajlandia'),
('TJS', '972', '2', 'Somoni', ' Tadżykistan'),
('TMT', '934', '2', 'Manat turkmeński', ' Turkmenistan'),
('TND', '788', '3', 'Dinar tunezyjski', ' Tunezja'),
('TOP', '776', '2', 'Paʻanga', ' Tonga'),
('TRY', '949', '2', 'Lira turecka', ' Turcja'),
('TTD', '780', '2', 'Dolar Trynidadu i Tobago', ' Trynidad i Tobago'),
('TWD', '901', '2', 'Dolar tajwański', ' Republika Chińska'),
('TZS', '834', '2', 'Szyling tanzański', ' Tanzania'),
('UAH', '980', '2', 'Hrywna', ' Ukraina'),
('UGX', '800', '0', 'Szyling ugandyjski', ' Uganda'),
('USD', '840', '2', 'Dolar amerykański', ' Stany Zjednoczone,  Barbados (BB) (jak również Dolar barbadoski),  Bermudy (BM) (jak również Dolar bermudzki),  Brytyjskie Terytorium Oceanu Indyjskiego (IO) (używane również GBP),  Brytyjskie Wyspy Dziewicze (VG),  Dalekie Wyspy Mniejsze Stanów Zjednoczonych (UM),  Ekwador (EC),  Guam (GU),  Haiti (HT),  Bonaire, Sint Eustatius i Saba (BQ – Bonaire, Sint Eustatius i Saba),  Mariany Północne (MP),  Mikronezja (FM),  Palau (PW),  Panama (PA) (jak również Balboa),  Portoryko (PR),  Salwador (SV),  Samoa Amerykańskie (AS),  Timor Wschodni (TL),  Turks i Caicos (TC),  Wyspy Dziewicze Stanów Zjednoczonych (VI),  Wyspy Marshalla (MH)'),
('USN', '997', '2', 'Dolar amerykański (next day)', ' Stany Zjednoczone'),
('UYI', '940', '0', 'Uruguay Peso en Unidades Indexadas (URUIURUI)', ' Urugwaj'),
('UYU', '858', '2', 'Peso urugwajskie', ' Urugwaj'),
('UYW', '927', '4', 'Unidad previsional', ' Urugwaj'),
('UZS', '860', '2', 'Sum', ' Uzbekistan'),
('VES', '928', '2', 'Boliwar', ' Wenezuela'),
('VND', '704', '0', 'Đồng', ' Wietnam'),
('VUV', '548', '0', 'Vatu', ' Vanuatu'),
('WST', '882', '2', 'Tala', ' Samoa'),
('XAF', '950', '0', 'Frank CFA', ' Czad (TD),  Gabon (GA),  Gwinea Równikowa (GQ),  Kamerun (CM),  Kongo (CG),  Republika Środkowoafrykańska (CF)'),
('XAG', '961', '.', 'Srebro (jedna uncja trojańska)', ''),
('XAU', '959', '.', 'Złoto (jedna uncja trojańska)', ''),
('XBA', '955', '.', 'Europejska Jednostka Rozrachunkowa (EURCO) (jednostka na rynku obligacji)', ''),
('XBB', '956', '.', 'Europejska Jednostka Rozrachunkowa (E.M.U.-6) (jednostka na rynku obligacji)', ''),
('XBC', '957', '.', 'Europejska Jednostka Rozrachunkowa (E.U.A.-9) (jednostka na rynku obligacji)', ''),
('XBD', '958', '.', 'Europejska Jednostka Rozrachunkowa (E.U.A.-17) (jednostka na rynku obligacji)', ''),
('XCD', '951', '2', 'Dolar wschodniokaraibski', ' Anguilla (AI),  Antigua i Barbuda (AG),  Dominika (DM),  Grenada (GD),  Montserrat (MS),  Saint Kitts i Nevis (KN),  Saint Lucia (LC),  Saint Vincent i Grenadyny (VC)'),
('XDR', '960', '.', 'Specjalne prawa ciągnienia', 'Międzynarodowy Fundusz Walutowy'),
('XOF', '952', '0', 'Frank CFA', ' Benin (BJ),  Burkina Faso (BF),  Gwinea Bissau (GW),  Mali (ML),  Niger (NE),  Senegal (SN),  Togo (TG),  Wybrzeże Kości Słoniowej (CI)'),
('XPD', '964', '.', 'Pallad (jedna uncja trojańska)', ''),
('XPF', '953', '0', 'Frank CFP', 'Francuskie Kolonie na Pacyfiku:  Nowa Kaledonia (NC),  Polinezja Francuska (PF),  Wallis i Futuna (WF)'),
('XPT', '962', '.', 'Platyna (jedna uncja trojańska)', ''),
('XSU', '994', '.', 'SUCRE', 'Ujednolicony system rozliczeń międzypaństwowych (SUCRE)'),
('XTS', '963', '.', 'Kod zarezerwowany do celów testowych', ''),
('XUA', '965', '.', 'Afrykański Bank Rozwoju', 'Afrykański Bank Rozwoju'),
('XXX', '999', '.', 'Brak waluty', ''),
('YER', '886', '2', 'Rial jemeński', ' Jemen'),
('ZAR', '710', '2', 'Rand', ' Lesotho,  Namibia,  Południowa Afryka'),
('ZMW', '967', '2', 'Kwacha zambijska', ' Zambia'),
('ZWL', '932', '2', 'Dolar Zimbabwe', ' Zimbabwe');